CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE TRANSACAO (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    VALOR NUMERIC(9,2) NOT NULL,
    DATAHORA TIMESTAMP WITH TIME ZONE NOT NULL
);